version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017" # MongoDB port
    volumes:
      - mongodb_data:/data/db # Persist data in a Docker volume
    environment:
      MONGO_INITDB_DATABASE: my_database # Optional: Create a default database
      MONGO_INITDB_ROOT_USERNAME: TrendlyAdmin # Optional: Admin username
      MONGO_INITDB_ROOT_PASSWORD: TrendlyAdminSecret # Optional: Admin password

volumes:
  mongodb_data:
    driver: local
